require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  SuggestExtensions: false


RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 8

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
