require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  SuggestExtensions: false
  NewCops: enable


RSpec/MultipleExpectations:
  Max: 4
RSpec/ExampleLength:
  Max: 8
RSpec/NestedGroups:
  Max: 4
RSpec/IndexedLet:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
