default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dinner_time_development

test:
  <<: *default
  database: dinner_time_test

# DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  database: dinner_time_production
  username: dinner_time
  password: <%= ENV["DINNER_TIME_DATABASE_PASSWORD"] %>
